name: Measure Temperature

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  Main:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo $(date)
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - name: Install dependencies
        run: go get .
      - name: Run main to grab temp
        run: |
          go run main.go
